apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: '-2'
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: dev project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns
            targetRevision: '1.9.0'
            valuesFile: apps/external-dns/dev-values.yaml
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://kedacore.github.io/charts
            targetRevision: '2.4.0'
            valuesFile: apps/keda/dev-values.yaml
            destNamespace: keda
          # ... add additional entries for your other Helm charts
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        helm:
          valueFiles:
            - 'apps/{{chart}}/common-values.yaml'
            - '{{valuesFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
