apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: '-2'
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: dev project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
status: {}

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            targetRevision: HEAD
            chartPath: charts/external-dns
            chartVersion: 'v0.16.0'
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            targetRevision: HEAD
            chartPath: charts/keda
            chartVersion: 'v2.4.0'
            destNamespace: keda
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - 'common.values.yaml'
            - 'dev.values.yaml'
          # This allows overriding the dependency version in the umbrella chart
          parameters:
            - name: dependencies[0].version
              value: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
