apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-non-core-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git # Replace with your actual GitHub repo URL
            targetRevision: HEAD
            chartPath: charts/external-dns
            chartVersion: 'v0.16.1' # Note the different version for prod
            valuesFile: app-values/external-dns/prod.values.yaml
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            targetRevision: HEAD
            chartPath: charts/keda
            chartVersion: 'v2.4.1' # Note the different version for prod
            valuesFile: app-values/keda/prod.values.yaml
            destNamespace: keda
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: prod
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - '../../../app-values/{{chart}}/common.values.yaml'
            - '../../../{{valuesFile}}'
          # This allows overriding the dependency version in the umbrella chart
          parameters:
            - name: dependencies[0].version
              value: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
        createNamespace: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
