apiVersion: v2
name: external-dns
description: An umbrella Helm chart for deploying external-dns in Kubernetes
type: application
version: 0.1.0
appVersion: '1.16.0'

# Dependencies represent charts that this umbrella chart depends on
dependencies:
  - name: external-dns
    version: '=1.16.0'
    repository: 'https://kubernetes-sigs.github.io/external-dns/'
