apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns'
    chart: external-dns
    targetRevision: "1.9.0"   # Specify the chart version you wish to deploy
    helm:
      releaseName: external-dns
      # Optionally, you can provide custom values:
      # values: |
      #   service:
      #     type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true