apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns
            targetRevision: '1.9.0'
            valuesFile: app-values/external-dns/dev-values.yaml
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://kedacore.github.io/charts
            targetRevision: '2.4.0'
            valuesFile: app-values/keda/dev-values.yaml
            destNamespace: keda
          # ... add additional entries for your other Helm charts
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.targetRevision}}'
        chart: '{{.chart}}'
        helm:
          valueFiles:
            - 'app-values/{{.chart}}/common.values.yaml'
            - 'app-values/{{.chart}}/dev.values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
