apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns
            targetRevision: '0.16.0'
            valuesFile: app-values/external-dns/dev-values.yaml
            destNamespace: external-dns
            destServer: https://kubernetes.default.svc
          - name: keda
            chart: keda
            repoURL: https://kedacore.github.io/charts
            targetRevision: '2.4.0'
            valuesFile: app-values/keda/dev-values.yaml
            destNamespace: keda
            destServer: https://kubernetes.default.svc
          # ... add additional entries for your other Helm charts
