apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            targetRevision: '2.16.0'
            valuesFile: apps/keda/dev.values.yaml
  template:
    metadata:
      name: keda-{{name}}
      env: { { name } }
    spec:
      project: default
      source:
        repoURL: 'https://kedacore.github.io/charts.git'
        targetRevision: { { targetRevision } }
        chart: keda
        helm:
          valueFiles:
            - apps/keda/common-values.yaml
            - { { valuesFile } }
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: keda
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
