apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj-labs/argocd-autopilot/manifests/base?ref=v0.4.19
configMapGenerator:
  - behavior: merge
    literals:
      - |
        repository.credentials=- passwordSecret:
            key: git_token
            name: autopilot-secret
          url: https://github.com/
          usernameSecret:
            key: git_username
            name: autopilot-secret
    name: argocd-cm
