apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.10.3
  - project-definitions.yaml
configMapGenerator:
  - behavior: merge
    literals:
      - |
        repository.credentials=- passwordSecret:
            key: password
            name: github-repo-creds
          url: https://github.com/
          usernameSecret:
            key: username
            name: github-repo-creds
      - |
        accounts.argo-test=apiKey,login
    name: argocd-cm
  - behavior: merge
    literals:
      - policy.default=role:readonly
      - |
        policy.csv=g, argo-test, role:admin
    name: argocd-rbac-cm
