# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns/
            destNamespace: external-dns
            env: dev
            chartVersion: '1.15.2'
            function: networking
            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - RespectIgnoreDifferences=true
                - AllowDowngrade=true
          - chart: keda
            repoURL: https://kedacore.github.io/charts
            destNamespace: keda
            env: dev
            chartVersion: 'v2.4.0'
            function: autoscaling
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - RespectIgnoreDifferences=true
                - AllowDowngrade=true
          - chart: helm-guestbook
            repoURL: https://github.com/argoproj/argocd-example-apps
            destNamespace: argo-guestbook
            env: dev
            chartVersion: HEAD
            function: frontend
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - RespectIgnoreDifferences=true
                - AllowDowngrade=true
  ## The template section defines the common properties for all applications.
  ## Changes to the template section will be applied to all applications, use caution!
  template:
    metadata:
      name: '{{chart}}-{{env}}'
      labels:
        app.kubernetes.io/name: '{{chart}}'
        app.kubernetes.io/instance: '{{chart}}-{{env}}'
        environment: '{{env}}'
        team: 'k8s-team'
        function: '{{function}}'
        chart-version: '{{chartVersion}}'
      annotations:
        argocd.argoproj.io/helm-version: v3
    spec:
      project: '{{env}}-non-core'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy: '{{syncPolicy}}'
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{chartVersion}}'
          chart: '{{chart}}'
          helm:
            releaseName: '{{chart}}'
            valueFiles:
              - $values/charts/{{chart}}/common.values.yaml
              - $values/charts/{{chart}}/{{env}}.values.yaml
        - repoURL: 'https://github.com/k-weaver/argo-demo.git'
          targetRevision: 'HEAD'
          ref: values
