# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/external-dns
            destNamespace: external-dns
            valuesFile: dev
            targetRevision: HEAD
            # Specific chart version we want to deploy
            chartVersion: '1.15.2'
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/keda
            destNamespace: keda
            valuesFile: dev
            targetRevision: HEAD
            # Specific chart version we want to deploy
            chartVersion: 'v2.4.0'
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-options: Validate=false,RespectIgnoreDifferences=true
        argocd.argoproj.io/helm-version: v3
    spec:
      project: dev-non-core
      source:
        repoURL: '{{repoURL}}'
        path: '{{chartPath}}'
        targetRevision: '{{targetRevision}}'
        helm:
          # Use the specific chart version through the releaseName property
          releaseName: '{{name}}'
          valueFiles:
            - 'common.values.yaml'
            - '{{valuesFile}}.values.yaml'
          version: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
