# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - list:
        elements:
          - chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns/
            destNamespace: external-dns
            env: dev
            chartVersion: '1.15.2'
            function: networking
            autoSync: false
            createNamespace: true
          - chart: keda
            repoURL: https://kedacore.github.io/charts
            destNamespace: keda
            env: dev
            chartVersion: 'v2.4.0'
            function: autoscaling
            autoSync: true
            prune: true
            selfHeal: true
            createNamespace: true
            applyOutOfSyncOnly: true
          - chart: hello-world
            repoURL: https://helm.github.io/examples
            destNamespace: sample-apps
            env: dev
            chartVersion: '0.1.0'
            function: frontend
            autoSync: true
            prune: true
            selfHeal: true
            createNamespace: true
            applyOutOfSyncOnly: true
  ## The template section defines the common properties for all applications.
  ## Changes to the template section will be applied to all applications, use caution!
  template:
    metadata:
      name: '{{.chart}}-{{.env}}'
      labels:
        app.kubernetes.io/name: '{{.chart}}'
        app.kubernetes.io/instance: '{{.chart}}-{{.env}}'
        environment: '{{.env}}'
        team: 'k8s-team'
        function: '{{.function}}'
        chart-version: '{{.chartVersion}}'
      annotations:
        argocd.argoproj.io/helm-version: v3
    spec:
      project: '{{.env}}-non-core'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
      sources:
        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.chartVersion}}'
          chart: '{{.chart}}'
          helm:
            releaseName: '{{.chart}}'
            valueFiles:
              - $values/charts/{{.chart}}/common.values.yaml
              - $values/charts/{{.chart}}/{{.env}}.values.yaml
        - repoURL: 'https://github.com/k-weaver/argo-demo.git'
          targetRevision: 'HEAD'
          ref: values
    templatePatch: |
      {{- if .autoSync }}
        syncPolicy:
          automated:
            {{- if .prune }}
            prune: true
            {{- else }}
            prune: false
            {{- end }}
            {{- if .selfHeal }}
            selfHeal: true
            {{- else }}
            selfHeal: false
            {{- end }}
          syncOptions:
            {{- if .createNamespace }}
            - CreateNamespace=true
            {{- else }}
            - CreateNamespace=false
            {{- end }}
            {{- if .applyOutOfSyncOnly }}
            - ApplyOutOfSyncOnly=true
            {{- else }}
            - ApplyOutOfSyncOnly=false
            {{- end }}
            - AllowDowngrade=true
      {{- else }}
        syncPolicy:
          syncOptions:
            {{- if .createNamespace }}
            - CreateNamespace=true
            {{- else }}
            - CreateNamespace=false
            {{- end }}
            {{- if .applyOutOfSyncOnly }}
            - ApplyOutOfSyncOnly=true
            {{- else }}
            - ApplyOutOfSyncOnly=false
            {{- end }}
            - AllowDowngrade=true
      {{- end }}
