# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/external-dns
            destNamespace: external-dns
            valuesFile: dev
            # This controls which version of your umbrella chart is pulled from Git
            # Can be a tag, branch name, or commit hash
            targetRevision: v1.0.0
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/keda
            destNamespace: keda
            valuesFile: dev
            # This controls which version of your umbrella chart is pulled from Git
            # Can be a tag, branch name, or commit hash
            targetRevision: v1.0.0
  template:
    metadata:
      name: '{{name}}'
      annotations:
        # Validate=false is used to skip validation of the Helm chart, required when allowing downgrades
        # RespectIgnoreDifferences=true is used to respect the ignoreDifferences settings in the Application
        # This is required to prevent the ApplicationSet controller from overwriting the ignoreDifferences settings
        argocd.argoproj.io/sync-options: Validate=false,RespectIgnoreDifferences=true
        argocd.argoproj.io/helm-version: v3
    spec:
      project: dev-non-core
      source:
        repoURL: '{{repoURL}}'
        path: '{{chartPath}}'
        # Use the targetRevision from the generator element
        targetRevision: '{{targetRevision}}'
        helm:
          valueFiles:
            - 'common.values.yaml'
            - '{{valuesFile}}.values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
