# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            targetRevision: HEAD
            chartPath: charts/external-dns
            chartVersion: '1.16.0'
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            targetRevision: HEAD
            chartPath: charts/keda
            chartVersion: 'v2.4.0'
            destNamespace: keda
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: dev-non-core
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - 'common.values.yaml'
            - 'dev.values.yaml'
          parameters:
            - name: dependencies[0].version
              value: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
