# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - chart: external-dns
            repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
            destNamespace: external-dns
            env: dev
            chartVersion: '1.15.2'
          - chart: keda
            repoURL: 'https://kedacore.github.io/charts'
            destNamespace: keda
            env: dev
            chartVersion: 'v2.4.0'
  template:
    metadata:
      name: '{{chart}}-{{env}}'
      labels:
        app.kubernetes.io/name: '{{chart}}'
        app.kubernetes.io/instance: '{{chart}}-{{env}}'
        environment: '{{env}}'
        team: 'k8s'
        tier: 'non-core'
        chart-version: '{{chartVersion}}'
      annotations:
        argocd.argoproj.io/helm-version: v3
    spec:
      project: '{{env}}-non-core'
      source:
        repoURL: '{{repoURL}}'
        path: '{{chartPath}}'
        targetRevision: '{{chartVersion}}'
        helm:
          releaseName: '{{chart}}-{{env}}'
          valueFiles:
            - 'git://https://github.com/k-weaver/argo-demo?path=charts/{{chart}}/common.values.yaml'
            - 'git://https://github.com/k-weaver/argo-demo?path=charts/{{chart}}/{{env}}.values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
