# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns/
            valuesRepo: https://github.com/k-weaver/argo-demo.git
            destNamespace: external-dns
            env: dev
            targetRevision: HEAD
            chartVersion: '1.15.2'
            function: networking
          - name: keda
            chart: keda
            repoURL: https://kedacore.github.io/charts
            valuesRepo: https://github.com/k-weaver/argo-demo.git
            destNamespace: keda
            env: dev
            targetRevision: HEAD
            chartVersion: 'v2.4.0'
            function: autoscaling
  template:
    metadata:
      name: '{{name}}-{{env}}'
      labels:
        app.kubernetes.io/name: '{{chart}}'
        app.kubernetes.io/instance: '{{chart}}-{{env}}'
        environment: '{{env}}'
        team: 'k8s-team'
        function: '{{function}}'
        chart-version: '{{chartVersion}}'
      annotations:
        argocd.argoproj.io/helm-version: v3
    spec:
      project: '{{env}}-non-core'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{chartVersion}}'
        chart: '{{chart}}'
        helm:
          releaseName: '{{chart}}'
          valueFiles:
            - $values/charts/{{chart}}/common.values.yaml
            - $values/charts/{{chart}}/{{env}}.values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
      sources:
        - repoURL: '{{valuesRepo}}'
          targetRevision: '{{targetRevision}}'
          ref: values
