# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/external-dns
            destNamespace: external-dns
            valuesFile: dev
            targetRevision: HEAD
            # Explicitly define the chart version - this overrides what's in Chart.yaml
            chartVersion: '1.15.2'
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/keda
            destNamespace: keda
            valuesFile: dev
            targetRevision: HEAD
            # Explicitly define the chart version - this overrides what's in Chart.yaml
            chartVersion: 'v2.4.0'
  template:
    metadata:
      name: '{{name}}'
      annotations:
        # Validate=false is used to skip validation of the Helm chart, required when allowing downgrades
        # RespectIgnoreDifferences=true is used to respect the ignoreDifferences settings in the Application
        argocd.argoproj.io/sync-options: Validate=false,RespectIgnoreDifferences=true
        argocd.argoproj.io/helm-version: v3
    spec:
      project: dev-non-core
      source:
        repoURL: '{{repoURL}}'
        path: '{{chartPath}}'
        targetRevision: '{{targetRevision}}'
        helm:
          valueFiles:
            - 'common.values.yaml'
            - '{{valuesFile}}.values.yaml'
          # Use parameters to override the dependency version
          parameters:
            # This effectively tells Helm to use this version when installing the dependency
            # This overrides the version in Chart.yaml
            - name: 'dependencies[0].version'
              value: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
