# This file defines the ArgoCD ApplicationSet for the dev project.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-non-core-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  generators:
    - list:
        elements:
          - name: external-dns
            chart: external-dns
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/external-dns
            chartVersion: '1.16.0'
            destNamespace: external-dns
          - name: keda
            chart: keda
            repoURL: https://github.com/k-weaver/argo-demo.git
            chartPath: charts/keda
            chartVersion: 'v2.4.0'
            destNamespace: keda
  template:
    metadata:
      name: '{{name}}'
      annotations:
        # Validate=false is used to skip validation of the Helm chart, required when allowing downgrades
        # RespectIgnoreDifferences=true is used to respect the ignoreDifferences settings in the Application
        # This is required to prevent the ApplicationSet controller from overwriting the ignoreDifferences settings
        argocd.argoproj.io/sync-options: Validate=false,RespectIgnoreDifferences=true
        argocd.argoproj.io/helm-version: v3
    spec:
      project: dev-non-core
      source:
        repoURL: '{{repoURL}}'
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - 'common.values.yaml'
            - 'dev.values.yaml'
          parameters:
            - name: dependencies[0].version
              value: '{{chartVersion}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - AllowDowngrade=true
