apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Basic ArgoCD installation manifests
# Source: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
---
# Add placeholder to indicate this is where you'd include the rest of the ArgoCD install manifests
# In a real installation, you would include the complete install.yaml from ArgoCD's GitHub repository
# This is truncated for brevity but should be replaced with the full manifests when applied
